apiVersion: v1
kind: Service
metadata:
  name: k8-service
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 32080
    port: 81
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
