apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redispod
  namespace: web
spec:
  containers:
  - image: redis
    name: redispod
    ports:
    - containerPort: 9090
      protocol: TCP
